[package]
name = "auction_measure"
description = "time measure, Rebuilt for Scale"
version = "1.0.0"
documentation = "https://docs.rs/rust-auction/measure"
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.14"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
